// Generated by LiveScript 1.2.0
var check;
check = function(bv, z, x, y){
  var yv, dx, o, v;
  if (!bv || !bv[z] || !bv[z][y]) {
    return false;
  }
  yv = bv[z][y];
  if (yv[0] > x || yv[1] < x) {
    return false;
  }
  dx = x - yv[0];
  o = parseInt(dx / 32);
  v = 1 << 31 - dx % 32;
  return yv[2][o] & v ? true : false;
};
if(!module) module = {};
module.exports = check;
